#!/usr/bin/perl
use Mojolicious::Lite;

get '/:fname/*lname' => [lname => [qw/ me you/]] => sub {
    shift->render('hello');
};

any [qw/ get post head patch/] => '/:fname/:lname' => sub {
    shift->render('hello');
};

app->start;

__DATA__

@@ hello.html.ep
<!doctype html>
<html>
    <head><title>Placeholder</title></head>
    <body>
        <i>Hello <%= $fname %> <%= $lname %>!</i>
        <br />
        <img src="/photo.jpg" />
    </body>
</html>

@@ hello.txt.ep
Hello <%= $fname %> <%= $lname %>

@@ hello.json.ep
("Hello":"<%= $fname %> <%= $lname %>}

@@ hello.xml.ep
<hello><%= $fname %> <%= $lname %></hello>
